# Generated by Django 5.0.1 on 2024-01-03 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cat_name", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_name", models.CharField(max_length=50)),
                ("ingredients", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("steps", models.CharField(max_length=255)),
                ("uploading_date", models.DateField()),
                ("image", models.ImageField(default="abc.jpg", upload_to="Images")),
                (
                    "cat_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.category",
                    ),
                ),
            ],
            options={
                "db_table": "Cake",
            },
        ),
    ]
