# Generated by Django 5.0.1 on 2024-01-03 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="recipe",
            table="recipe",
        ),
    ]
