# Generated by Django 5.0.1 on 2024-01-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0002_alter_recipe_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="steps",
            field=models.CharField(max_length=1000),
        ),
    ]
