# Generated by Django 5.0.1 on 2024-01-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0004_alter_recipe_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="shortinfo",
            field=models.CharField(default=0, max_length=100),
        ),
    ]
