# Generated by Django 5.0.1 on 2024-01-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0007_alter_recipe_shortinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="steps",
            field=models.TextField(),
        ),
    ]
