# Generated by Django 5.0.1 on 2024-01-05 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0009_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="profile",
        ),
    ]
