# Generated by Django 5.0.1 on 2024-01-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
