# Generated by Django 5.0.1 on 2024-01-05 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0002_alter_profile_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="profile",
        ),
    ]
