# Generated by Django 5.0.1 on 2024-01-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0004_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="profiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=35)),
                ("password", models.CharField(max_length=10)),
                ("email", models.CharField(max_length=20)),
                ("number", models.CharField(max_length=12)),
            ],
            options={
                "db_table": "profiles",
            },
        ),
        migrations.DeleteModel(
            name="profile",
        ),
    ]
