# Generated by Django 5.0.1 on 2024-01-05 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0005_profiles_delete_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="profiles",
        ),
    ]
