# Generated by Django 5.0.1 on 2024-01-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0007_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiles",
            name="number",
            field=models.IntegerField(),
        ),
    ]
