# Generated by Django 5.0.1 on 2024-01-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0008_alter_profiles_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profiles",
            name="id",
        ),
        migrations.AlterField(
            model_name="profiles",
            name="email",
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name="profiles",
            name="number",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="profiles",
            name="username",
            field=models.CharField(max_length=35, primary_key=True, serialize=False),
        ),
    ]
