# Generated by Django 5.0.1 on 2024-01-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0009_remove_profiles_id_alter_profiles_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiles",
            name="number",
            field=models.BigIntegerField(max_length=12),
        ),
    ]
