# Generated by Django 5.0.1 on 2024-01-05 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0011_alter_profiles_number"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="profiles",
            table="profile",
        ),
    ]
