# Generated by Django 5.0.1 on 2024-01-05 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0012_alter_profiles_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="profiles",
            new_name="profile",
        ),
    ]
